#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnsl
Version  : 1.2.0
Release  : 2
URL      : https://github.com/thkukuk/libnsl/archive/v1.2.0.tar.gz
Source0  : https://github.com/thkukuk/libnsl/archive/v1.2.0.tar.gz
Summary  : Library containing NIS functions using TI-RPC (IPv6 enabled)
Group    : Development/Tools
License  : LGPL-2.1
Requires: libnsl-lib
BuildRequires : pkgconfig(libtirpc)

%description
See the file COPYING for copying restrictions.
This package contains the libnsl library. This library contains
the public client interface for NIS(YP) and NIS+.

%package dev
Summary: dev components for the libnsl package.
Group: Development
Requires: libnsl-lib
Provides: libnsl-devel

%description dev
dev components for the libnsl package.


%package lib
Summary: lib components for the libnsl package.
Group: Libraries

%description lib
lib components for the libnsl package.


%prep
%setup -q -n libnsl-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517889749
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1517889749
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/rpcsvc/yppasswd.h
%exclude /usr/include/rpcsvc/yppasswd.x
/usr/include/rpcsvc/nis.h
/usr/include/rpcsvc/nis.x
/usr/include/rpcsvc/nis_callback.h
/usr/include/rpcsvc/nis_callback.x
/usr/include/rpcsvc/nis_object.x
/usr/include/rpcsvc/nis_tags.h
/usr/include/rpcsvc/nislib.h
/usr/include/rpcsvc/yp.h
/usr/include/rpcsvc/yp.x
/usr/include/rpcsvc/yp_prot.h
/usr/include/rpcsvc/ypclnt.h
/usr/include/rpcsvc/ypupd.h
/usr/lib64/libnsl.so
/usr/lib64/pkgconfig/libnsl.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnsl.so.2
/usr/lib64/libnsl.so.2.0.0
