#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnsl
Version  : 2.0.0
Release  : 6
URL      : https://github.com/thkukuk/libnsl/releases/download/v2.0.0/libnsl-2.0.0.tar.xz
Source0  : https://github.com/thkukuk/libnsl/releases/download/v2.0.0/libnsl-2.0.0.tar.xz
Summary  : Library containing NIS functions using TI-RPC (IPv6 enabled)
Group    : Development/Tools
License  : LGPL-2.1
Requires: libnsl-lib = %{version}-%{release}
Requires: libnsl-license = %{version}-%{release}
BuildRequires : pkgconfig(libtirpc)

%description
See the file COPYING for copying restrictions.
This package contains the libnsl library. This library contains
the public client interface for NIS(YP) and NIS+.

%package dev
Summary: dev components for the libnsl package.
Group: Development
Requires: libnsl-lib = %{version}-%{release}
Provides: libnsl-devel = %{version}-%{release}
Requires: libnsl = %{version}-%{release}

%description dev
dev components for the libnsl package.


%package lib
Summary: lib components for the libnsl package.
Group: Libraries
Requires: libnsl-license = %{version}-%{release}

%description lib
lib components for the libnsl package.


%package license
Summary: license components for the libnsl package.
Group: Default

%description license
license components for the libnsl package.


%prep
%setup -q -n libnsl-2.0.0
cd %{_builddir}/libnsl-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672180468
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1672180468
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libnsl
cp %{_builddir}/libnsl-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libnsl/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/rpcsvc/yp.h
/usr/include/rpcsvc/yp.x
/usr/include/rpcsvc/yp_prot.h
/usr/include/rpcsvc/ypclnt.h
/usr/include/rpcsvc/yppasswd.h
/usr/include/rpcsvc/yppasswd.x
/usr/include/rpcsvc/ypupd.h
/usr/lib64/libnsl.so
/usr/lib64/pkgconfig/libnsl.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnsl.so.3
/usr/lib64/libnsl.so.3.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libnsl/01a6b4bf79aca9b556822601186afab86e8c4fbf
